### ISSUE TITLE
Do you need GUI?

### ISSUE THREAD

**Issue by topilski** [EQ-Alpha/KeyDB#12]
Hi, do you need gui for KeyDB?

**Comment by JohnSully** [comment]
You create FastoRedis right?

We have some new features in the pipe that definitely could use a GUI. The obvious first one is an image data type we are working on - would be great to actually see a thumbnail. 

We could also expose data on load and threads if that makes sense to visualize.

**Comment by topilski** [comment]
Yes, FastoRedis is part of [FastoNoSQL](https://github.com/fastogt/fastonosql) , it simple to add driver based on hiredis. Yes i think it is possible, how to receive threads count? Or get threads info from server?

**Comment by JohnSully** [comment]
I've added the following information to the INFO command in change ac80a5c6a.

**Under the CPU section**

server_threads:
   Pretty straight foward, the number of threads server threads from the configuration file.

long_lock_waits:
   This is used to diagnose cases where CPU cycles are being wasted in locks (e.g. if KeyDB is configured with too many threads).  A large value here suggest the number of server threads should be reduced.  This number increments monotonically from the start of the process.

**Under the Clients Section**
thread_N_clients:[Num clients]
e.g.
thread_0_clients:2
thread_1_clients:0

This shows the distribution of clients to threads.

As I mentioned before - when we get our image feature up this will be improved with proper GUI support so I'm really interested in working with you on that one.  If you think of any other stats that might be interesting let me know and I can add support for them.

**Comment by topilski** [comment]
To start implementation i need logo for your db, and list of command which KeyDB support.

**Comment by topilski** [comment]
I think can be used Redis driver, but need to change icon and remove modules support, KeyDB have sentinels, clusters?

![Screenshot from 2019-03-19 22-31-07](https://user-images.githubusercontent.com/4686379/54655516-9bbf4a00-4a98-11e9-99c8-6696bb94b9e4.png)

**Comment by JohnSully** [comment]
Yes KeyDB supports every Redis feature and is fully compatible with everything that supports Redis 5 including modules, sentinels, clusters, etc.  Our goal is to add more features not take any away :)

HiRedis will work, however the version compiled in our tree will begin to have support for new features as we add them.  I guess we'll have to rename it at some point to HiKeyDB.  

KeyDB's logo is currently this cloud ![logo](https://www.eqalpha.com/img/cloudtransparent.png)

**Comment by JohnSully** [comment]
Also we have a wider logo: ![logo](https://www.eqalpha.com/img/keydb.png)

**Comment by topilski** [comment]
@JohnSully thank you for description. You have cool project!

**Comment by topilski** [comment]
Hey @JohnSully why default port is 6379?

**Comment by JohnSully** [comment]
It’s inherited from Redis. In general keyDB is a superset of Redis.

**Comment by topilski** [comment]
Ok, here branch where i start development for KeyDB https://github.com/fastogt/fastonosql_core/tree/keydb_api

**Comment by topilski** [comment]
Done: 
![keydb_first](https://user-images.githubusercontent.com/4686379/55286015-9dddae80-539e-11e9-8397-09cbc609ae11.png)

I need to do some tests and merge it to master.

**Comment by topilski** [comment]
@JohnSully i released [FastoNoSQL](https://github.com/fastogt/fastonosql/releases/tag/v2.2.0) with KeyDB support.

**Comment by JohnSully** [comment]
This is awesome!  I can't wait to get this image feature out, its going to work great with your GUI.

**Comment by topilski** [comment]
@JohnSully you are welcome, will wait your feedback.
