### ISSUE TITLE
Keydb 6.0.8 RC1 make test failed on ARM with CentOS 8

### ISSUE THREAD

**Issue by hengku** [EQ-Alpha/KeyDB#193]
I tried to run make test against Keydb 6.0.8 RC1 on the ARM server with CentOS 8, but it failed at replication.tcl.  The make test passed on the x86 server with Ubuntu 18.04. Below is the error message: 

!!! WARNING The following tests failed:

*** [err]: replica buffer don't induce eviction in tests/integration/replication.tcl
Expected 17186 > 2*1024*1024 (context: type eval line 65 cmd {assert {$slave_buf > 2*1024*1024} } proc ::test)
Cleanup: may take some time... OK
make[1]: *** [Makefile:376: test] Error 1

**Comment by JohnSully** [comment]
Hi @hengku 

This test is notoriously flaky.  It generally fails with high CPU load.  I have it as a backlog to resolve it.

**Comment by christianEQ** [comment]
I believe the flakiness of this test has been resolved now, and I've confirmed that it passes consistently on ARM CentOS 8. Closing.
