### ISSUE TITLE
Active - Active : Reversed Key values

### ISSUE THREAD

**Issue by mcineran** [EQ-Alpha/KeyDB#247]
Hi, a simple 2 member Active - Active, as per the documentation.

Host1:
Writes    key: thehostname, value: Host1

Host2:
Writes    key: thehostname, value: Host2

This happens to occur at the exact same time.

The results is:

Host1:
Key: thehostname, value: Host2

Host2:
Key: thehostname, value: Host1

Obviously the preference is that one would win and overwrite, block the other write. That is, I do not need one value to win, I need to stop one of the writes from being successful.

The code that does that, checks if the Key exists before attempting to create it with the value. Open to suggestions to fix the code :).

In the mean time i've put a HAproxy in front of it to queue all writes to 1 and fail to the other if it fails.

There might be a better simple dual HA configuration I can use? Maybe standard multi-master with readonly replica?
I really need to be able to bounce these hosts up and down and not to have to deal with things like a broken redis cluster :D

**Comment by JohnSully** [comment]
Clock skew is resulting in them not converging. I had a plan to implement synchronization and it looks like its about time to implement it. 

The original plan for Active Rep was to support what you described, send all traffic to one node and failover to the other without needing sentinel to promote.

**Comment by krunkosaurus** [comment]
What is the point of multi-master without CRDT feature? They would just be overwriting each other or worse, what OP just experienced.

I was blown away that KeyDB had achieved master-master but I've yet to see a good use case of the current implementation. I think KeyDB should *star it's homepage when mentioning master-master and say "CRDT-pending" to not get everyone excited. 

Also consider starting a Gitcoin for this project as I know many people as well as myself would sponsor this feature. https://gitcoin.co/

https://github.com/EQ-Alpha/KeyDB/issues/47 can't come sooner.

Thanks.

**Comment by VivekSainiEQ** [comment]
Since RAFT is an active work in progress, and would fix this issue as well as CRDTs would, closing this issue and tracking with #349 instead.
