### ISSUE TITLE
Celery workers receive duplicate messages

### ISSUE THREAD

**Issue by qeternity** [EQ-Alpha/KeyDB#258]
**Describe the bug**
It's tough to call this a bug as I think it's pretty obvious that it's just a function of the design choices that have been made, but given keydb's apparent goal to be drop-in for redis, I wanted to reach out and see if there is a workaround (I didn't see anything in the docs).

With Celery, it seems that each task that is published winds up on every keydb node at which point a worker is able to consume the task. However if running X nodes, with Y workers (where Y >= X with each connecting to a different node), tasks will end up being run X times.

One of keydb's greatest strengths imo is that it provides clustering while speaking plain redis (as opposed to redis sentinel or redis cluster). Third-party library support (especially in the python/django space) for sentinel/cluster is lacking to say the least. Is there a way to make keydb follower nodes purely for failover?

**To Reproduce**
Start n > 1 master-master keydb instances with n > 1 celery workers where each worker connects to a different keydb node

**Comment by macropin** [comment]
We've seen similar behaviour with https://github.com/coleifer/huey. The jobs get duplicated by the number of masters when running in multi-master mode.

**Comment by qeternity** [comment]
@JohnSully any tips or tricks that would help with this? Or is this a fundamental limitation of master-master replication?

**Comment by JohnSully** [comment]
As an update I consider this a bug and we’re working on a fix. We’re just going through a backlog first so it will take a bit more time before I’m able to dig into this.

**Comment by qeternity** [comment]
Many thanks!

**Comment by ivan046** [comment]
@JohnSully can you provide approximate estimate for this bugfix? Half a year or more? Just for a future plan, as that blocks us from migrating Redis Sentinel (+haproxy) HA to KeyDB Active-Replica HA setup.

**Comment by JohnSully** [comment]
I think this is going to take a while.  We are working internally on a RAFT implementation but this is quite involved.  I don't think it's possible to get the consistency needed without a stronger protocol in place.  Active Rep as it currently exists still works well for other use cases where such strong consistency is not needed and will be more performant in those scenarios so we will also keep this mode as well.

**Comment by VivekSainiEQ** [comment]
As stated above, we're implementing RAFT to solve this issue. Closing this issue and tracking with #349 instead.
