### ISSUE TITLE
Support for RedisInsight (or any other web based admin panel)

### ISSUE THREAD

**Issue by nhaberl** [EQ-Alpha/KeyDB#304]
Are there any plans to create or support any kind of web based admin panel like https://redislabs.com/redis-enterprise/redis-insight/ or similar?

**Comment by yegors** [comment]
This tool is better than Redis Insights: https://rdm.dev

**Comment by VivekSainiEQ** [comment]
I cannot speak to future plans to create a web based admin panel, however KeyDB should work out of the box with existing admin panels for Redis.
