### ISSUE TITLE
LOADING Redis is loading the dataset in memory

### ISSUE THREAD

**Issue by curtbushko** [EQ-Alpha/KeyDB#308]
I am running keydb in kubernetes. A very simple setup using the helm chart with 2 pods with the following startup configuration. 

Keydb 6.0.16

```
exec keydb-server /etc/keydb/redis.conf \
  --active-replica yes \
  --multi-master yes \
  --rdbcompression no \
  --bind 0.0.0.0 \
  --port "${PORT}" \
  --protected-mode no \
  --server-threads 1 \
  --repl-diskless-sync no \
  --repl-timeout 600 \
  --repl-ping-replica-period 30 \
  --repl-backlog-size 250mb \
  --client-output-buffer-limit replica 500mb 256mb 120 \
  --client-output-buffer-limit slave 500mb 256mb 120 \
  --loglevel debug \
  "${REPLICAS[@]}"
```

- We are writing data into keydb and this error is coming up
- Redis docs tell you to 'retry'. We are, with a backoff and still getting this error
- This does NOT occur with 1 pod so we believe it has something to do with the 2 masters syncing.

Does anyone have recommendations for a high write setup that we can use or any setting that is wrong above?

I can create another pod just for writes but would it be possible to have my two other masters just tailing/sync'ing it?

(I don't have logs right now but I can get them tomorrow)

Thanks!

**Comment by Serpent6877** [comment]
I believe you are having similar issues to my bug report:

#309 

Let me know if that looks similar.

**Comment by curtbushko** [comment]
@Serpent6877 Our issue turned out to be istio's proxy causing disconnects. We have had several statefulset services where we have had to disable istio to get the performance we need.
