### ISSUE TITLE
Master-Master replication errors with large Redis 4.0.9 dump.rdb file.

### ISSUE THREAD

**Issue by Serpent6877** [EQ-Alpha/KeyDB#309]
OS: Ubuntu 18.04.5 LTS
KeyDB Version: 6.0.18-1-bionic1 from APT
DB's in Redis dump.rdb: 14
Dataset: hash and lists
Master-A: 2 x 8-core Xeon w/ 192GB RAM
Master-B: 1 x 8-core Xeon w/ 8GB RAM

1. Tested that servers replicate by starting them both up with blank DB's, doing several SET's and GET's. 
2. Issues occur when I copy over my 2.5GB Redis 4.0.9 dump file into /var/lib/keydb. I start first server (Master-A) file loads fine and log shows loading the 4.0.9 dump file. I can view keys, no errors on this server. 
3. I then start second server (Master-B) it connects up and starts to sync. Then Master-A spits out some CRITICAL "This replica is sending an error to its master: 'Invalid MVCC Tstamp' after processing the command 'KEYDB.MVCCRESTORE'" errors. Master-B will then going into a continuous resync loop. However if I connect to Master-B with keydb-cli I can see the data has loaded. It appears the two servers can't agree on the data being valid even though Master-B received a duplicate copy from Master-A. I tested this with a smaller subset of my data by doing a FLUSHDB on a copy of the redis data on 12 of the DB's. Thus only having 2 DB's worth of data (about 32MB worth) and this seemed to sync okay.

MASTER-A Config changes to default keydb.conf:
```
port 6390
save 900 1
# save 300 10
save 60 10000
masterauth testpass123
replica-read-only no
requirepass testpass123
server-threads 4
multi-master yes
active-replica yes
replicaof <Master-B IP> 6379
```

MASTER-B Config changes to default keydb.conf:
```
masterauth testpass123
replica-read-only no
requirepass testpass123
server-threads 4
multi-master yes
active-replica yes
replicaof <Master-A IP> 6390
```

Log files from both servers:
[http://45.43.30.2/downloads/keydb-server-logs.tar.gz](url)

I can give you a copy of my data to verify the issue if needed.

**Comment by Serpent6877** [comment]
Some tuning in my /etc/sysctl.conf that could impact tcp-backlog and syncing:
```
# Increase Linux autotuning TCP buffer limits
# Set max to 16MB for 1GE and 32M (33554432) or 54M (56623104) for 10GE
# Don't set tcp_mem itself! Let the kernel scale it based on RAM.
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.core.rmem_default = 16777216
net.core.wmem_default = 16777216
net.core.optmem_max = 40960
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
# Increase max connections for Redis
net.core.somaxconn = 65365

# Make room for more TIME_WAIT sockets due to more clients,
# and allow them to be reused if we run out of sockets
# Also increase the max packet backlog
net.ipv4.tcp_max_syn_backlog = 30000
net.ipv4.tcp_max_tw_buckets = 2000000
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_fin_timeout = 10
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 60
net.ipv4.tcp_keepalive_probes = 20
net.core.netdev_max_backlog = 60000
net.core.netdev_budget = 60000
net.core.netdev_budget_usecs = 6000

# If your servers talk UDP, also up these limits
net.ipv4.udp_rmem_min = 8192
net.ipv4.udp_wmem_min = 8192

# Change Congestion Control Algorithm to BBR
net.core.default_qdisc=fq
net.ipv4.tcp_congestion_control=bbr
```

Don't believe this will be an issue but it's the only additional items I can think of that might impact this. I do run UFW on these servers.

**Comment by Serpent6877** [comment]
#237

Is this related? I do see a large amount of the MVCC Timestamp errors in the logs when it attempts to replicate.

**Comment by Serpent6877** [comment]
So found the issue to this replication problem.

Error in log file shows:
```
8368:8377:S 29 Apr 2021 18:33:09.191 * RDB memory usage when created 5004.23 Mb
8368:8377:S 29 Apr 2021 18:33:26.462 # Client id=18 addr=45.43.30.2:36701 fd=34 name= age=252 idle=0 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=249 omem=269195096 tot-mem=269256560 events=rw cmd=replconf user=default scheduled to be closed ASAP for overcoming of output buffer limits.
8368:8377:S 29 Apr 2021 18:33:26.465 # Connection with replica 45.43.30.2:6390 lost.
```

You can see the error as "default scheduled to be closed ASAP for overcoming of output buffer limits". This is telling us that the client-output-buffer-limit for replica is too small. The default is:
```
client-output-buffer-limit replica 256mb 64mb 60
```

The format is:
```
client-output-buffer-limit <class> <hard limit> <soft limit> <soft seconds>
```

You can view your used memory with:
```
keydb-cli -p 6379 info memory
```

Initially I set the client-output-buffer-limit for replica to "0 0 0". This seemed to work. After testing I was able to set this limit to "4096mb 2048mb 60". Though I might have been able to tune this more. However I am curious if this will work with say a 10GB or even larger RDB file. Some adjustments need to be made to the default keydb.conf to handle large dumb.rdb files. I am sure others will run into this issue when trying to add additional masters to their already running configuration.

**Comment by VivekSainiEQ** [comment]
Looks like you've already solved this issue. Just to add, setting the client-output-buffer-limit for replica to "0 0 0"
