### ISSUE TITLE
Support `BLMOVE` and `LMOVE`

### ISSUE THREAD

**Issue by intech** [EQ-Alpha/KeyDB#310]
From Redis 6.2.0 added new commands comes in place of the now deprecated `RPOPLPUSH` and `BRPOPLPUSH`.
In the future, the softwares will lose compatibility with KeyDB.

Docs:
[LMOVE](https://redis.io/commands/lmove)
[BLMOVE](https://redis.io/commands/blmove)

**Comment by JohnSully** [comment]
Hey @intech we’re in the process of merging 6.2 now it will be in the next release. The last sync was 6.0.10 at that time 6.2 was still in RC so we waited.
