### ISSUE TITLE
Alpine build fails on unstable (latest) branch

### ISSUE THREAD

**Issue by dbpaul** [EQ-Alpha/KeyDB#325]
Following the instructions on https://docs.keydb.dev/docs/build/
....
git clone https://github.com/EQ-Alpha/KeyDB.git
make
....
debug.cpp: In function 'void backtrace_symbols_demangle_fd(void**, size_t, int)':
debug.cpp:1605:19: error: 'backtrace_symbols' was not declared in this scope
 1605 |     char **syms = backtrace_symbols(trace, csym);
.......................................^~~~~~~~~~~~~~~~~
debug.cpp:1625:24: error: 'abi' has not been declared
 1625 |             char *sz = abi::__cxa_demangle(symbuf, nullptr, nullptr, &status);
........................................ ^~~

**Comment by MalavanEQAlpha** [comment]
Fixed with PR #328
