### ISSUE TITLE
Does keydb work with redisearch?

### ISSUE THREAD

**Issue by hiqsociety** [EQ-Alpha/KeyDB#332]
Does keydb work with redisearch?

**Comment by hiqsociety** [comment]
in another issues, do all redis modules work with keydb?

**Comment by VivekSainiEQ** [comment]
Hi @hiqsociety,

In general, KeyDB is compatible with Redis modules, so RediSearch should work.

**Comment by hiqsociety** [comment]
in general <- can u specify the edge cases where redismodules wont work?

**Comment by VivekSainiEQ** [comment]
What I mean is that KeyDB is designed to be a drop-in replacement for Redis, and as such is intended to be fully compatible with the Redis ecosystem, including modules. However, bugs can arise from running Redis modules in KeyDB, particularly when modules employ their own threading model which runs alongside KeyDB's threads. The intended behaviour is that all modules run the same in KeyDB as they would in Redis, so if you encounter a bug when using any Redis modules (I'm guessing RediSearch in this case), I encourage you to open an issue so we can fix it.

**Comment by JohnSully** [comment]
@hiqsociety to reiterate what Vivek mentioned, we aim to make KeyDB fully compatible with modules.  Note however modules often don't get a speedup with KeyDB, as the threading model is designed to make core operations faster - not modules.
