### ISSUE TITLE
[BUG] redis compatible arguments for `lpop`/`rpop`

### ISSUE THREAD

**Issue by intech** [EQ-Alpha/KeyDB#335]
**Describe the bug**

In keydb, the [`lpop`](https://redis.io/commands/lpop) and [`rpop`](https://redis.io/commands/rpop) commands need one argument, in redis, two arguments - `key` and `count` (optional).

**To reproduce**

```bash
127.0.0.1:6379[1]> lpop proxies 3
(error) ERR wrong number of arguments for 'lpop' command
127.0.0.1:6379[1]> rpop proxies 3
(error) ERR wrong number of arguments for 'rpop' command
```

**Expected behavior**

Support redis compatible: `lpop key [count]` and `rpop key [count]`

**Additional information**

```bash
# Server
redis_version:6.0.18
redis_git_sha1:bf5b2d78
redis_git_dirty:1
redis_build_id:45f35a734837d10b
```

**Comment by JohnSully** [comment]
Hi @intech this is a recent Redis change which is merged into the unstable branch.  We're prepping a release in the next week which should publish it.  In the meantime its possible to use our unstable docker images or build from source to access it early.
