### ISSUE TITLE
Docker latest image no more updated?

### ISSUE THREAD

**Issue by JarmoSa** [EQ-Alpha/KeyDB#351]
Looks like docker image "latest" have been updated last time 5 months ago. Is the only available container now "unstable"?

It would be nice to have latest release versions available in docker too.

**Comment by JarmoSa** [comment]
Also DEB packages are not updated. The last available version there is 6.0.18

**Comment by benschermel** [comment]
Hi @JarmoSa, 

We are performing some final tests on the various distributions and expect deb/rpm/docker builds to be published by Monday. Will close this once published.

**Comment by benschermel** [comment]
All distribution packages (docker/deb/rpm/ppa) are updated for KeyDB and KeyDB Pro for version 6.2.0.
