### ISSUE TITLE
[QUESTION] Replication Offset

### ISSUE THREAD

**Issue by tuhuynh27** [EQ-Alpha/KeyDB#358]
Related to [https://docs.keydb.dev/docs/replication](https://docs.keydb.dev/docs/replication)

How is the replication offset is incremented?

In the case of Redis, its storage engine is single-threaded (Redis 6 is only multi-thread at I/O threads, the store is still handled single-threaded), so it's easy to maintain the incremental offset of the buffer because there are **no concurrent writes to the store**.

```
0 SET a b
1 SET a c
2 SET a d
```

In the case of KeyDB, I think the storage engine is something like ConcurrentHashmap right? So it would **allow concurrent writes to the store**, and how to maintain the offset then?

**Comment by VivekSainiEQ** [comment]
Hi @tuhuynh27,

Even though KeyDB is multi-threaded, access to the backing store is synchronized through the use of locks so only one thread will access it at a time. As a result, the incremental offset is handled in a similar way to Redis.
