### ISSUE TITLE
[BUG] libunwind-dev missing for alpine build instructions

### ISSUE THREAD

**Issue by dbpaul** [EQ-Alpha/KeyDB#360]
**Describe the bug**

debug.cpp:56:10: fatal error: libunwind.h: No such file or directory
   56 | #include <libunwind.h>
 

**To reproduce**

Following the instructions on https://docs.keydb.dev/docs/build/
apk add --no-cache coreutils gcc linux-headers make musl-dev util-linux-dev openssl-dev curl-dev g++ bash git perl
git clone https://github.com/EQ-Alpha/KeyDB.git
cd KeyDB
make
....  libunwind.h: No such file or directory

apk add libunwind-dev
=> all ok

**Comment by VivekSainiEQ** [comment]
Hi @dbpaul,

I've put in a PR to fix the documentation to include the libunwind dependency for alpine.

**Comment by benschermel** [comment]
Thanks, this is published here: https://docs.keydb.dev/docs/build#alpine
