### ISSUE TITLE
src/modules cannot be build with clang

### ISSUE THREAD

**Issue by drook** [EQ-Alpha/KeyDB#363]
version: 6.2.0

src/modules cannot be build with clang:

````
[root@dev:src/modules]# gmake
ld -o helloworld.so helloworld.xo -bundle -undefined dynamic_lookup  -lc
ld: error: unknown argument '-bundle'
ld: error: unable to find library -lc
gmake: *** [Makefile:24: helloworld.so] Error 1
````

**are they even needed for main functionality ?** I can successfully build 6.2.0 with clang with minor changes. The build passes all the bundled tests after that.

Env:
OS: FreeBSD 12.2, amd64,
Clang:
````
FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)
Target: x86_64-unknown-freebsd12.2
Thread model: posix
InstalledDir: /usr/bin
````

**Comment by VivekSainiEQ** [comment]
Hi @drook,

The modules found in src/modules are not needed for main functionality. I'm fairly certain they're there to serve as example code for the module API should you wish to write your own modules.

**Comment by drook** [comment]
Thanks.
