### ISSUE TITLE
[NEW] C API for embeded mode

### ISSUE THREAD

**Issue by Dan-Do** [EQ-Alpha/KeyDB#387]
**I dont need the whole standalone server mode**
**Description of the feature**
For example, I just need
```C
#include "keydb.h"
#include ...

my_db = keydb_open("path/to/file")
key = 123
val = keydb_get(key)
result = keydb_put(key, new_val)
```
Can I do that in the current source branch?

**Comment by VivekSainiEQ** [comment]
Hi @Dan-Do, 
Sorry for the very late response. Unfortunately KeyDB doesn't support a serverless mode, so the answer to your question is no.

**Comment by JohnSully** [comment]
@Dan-Do You cannot use KeyDB as an in process library as Vivek mentioned, but another option might be to write  your app as a module for KeyDB and implement it this way.  At its core KeyDB is a hash map (although it has other niceties like a save format you may want).  So the most direct way is to use your libraries hash map implementation, or take a look at the one from Redis/KeyDB which you'll find in dict.cpp/dict.h

Hope that helps,
-John
