### ISSUE TITLE
Don't compile KeyDB from source on Fedora 35

### ISSUE THREAD

**Issue by gvsafronov** [EQ-Alpha/KeyDB#396]
**Describe the bug**

Don't compile KeyDB from source.
Operating system: Linux Fedora 35
Kernel: 5.16.5-200.fc35.x86_64

**To reproduce**

1. git clone https://github.com/EQ-Alpha/KeyDB
2. cd KeyDB
3. Run 'make' in terminal

**Expected behavior**

When I started compilation, run 'make' in terminal, I see the follows errors:

In file included from server.h:83,
                 from server.cpp:31:
server.cpp: В функции «int clientsCronTrackExpansiveClients(client*, int)»:
zmalloc.h:58:25: ошибка: «je_malloc_usable_size» was not declared in this scope; did you mean «malloc_usable_size»?
   58 | #define zmalloc_size(p) je_malloc_usable_size(p)
      |                         ^~~~~~~~~~~~~~~~~~~~~
server.cpp:1816:34: замечание: в расширении макроса «zmalloc_size»
 1816 |                       (c->argv ? zmalloc_size(c->argv) : 0);
      |                                  ^~~~~~~~~~~~
server.cpp: В функции «int clientsCronTrackClientsMemUsage(client*)»:
zmalloc.h:58:25: ошибка: «je_malloc_usable_size» was not declared in this scope; did you mean «malloc_usable_size»?
   58 | #define zmalloc_size(p) je_malloc_usable_size(p)
      |                         ^~~~~~~~~~~~~~~~~~~~~
server.cpp:1836:12: замечание: в расширении макроса «zmalloc_size»
 1836 |     mem += zmalloc_size(c);
      |            ^~~~~~~~~~~~
На глобальном уровне:
cc1plus: замечание: unrecognized command-line option «-Wno-atomic-alignment» may have been intended to silence earlier diagnostics
make[1]: *** [Makefile:451: server.o] Ошибка 1
make[1]: выход из каталога «/home/grigoriy/fluidb/src»
make: *** [Makefile:6: all] Ошибка 2

**Additional information**

Any additional information that is relevant to the problem.

**Comment by benschermel** [comment]
Hi @gvsafronov 

I was able to build on fedora 35 with the following deps:
```
dnf install jemalloc-devel g++ libuuid-devel libatomic openssl-devel curl-devel
```
Please try installing with these... assuming you need jemalloc-devel but do not have translation of the above.

**Comment by benschermel** [comment]
Closing issue
