### ISSUE TITLE
Debian Binary Package

### ISSUE THREAD

**Issue by steamboatid** [EQ-Alpha/KeyDB#89]
Is there any debian binary package for this ?
or at least, where I can create a binary package from it

TIA

**Comment by benschermel** [comment]
Hi TIA, 

We have a PPA for it, you can check it out here: https://launchpad.net/~eqalpha/+archive/ubuntu/keydb-server 

You can run the package with:

sudo add-apt-repository ppa:eqalpha/keydb-server
sudo apt-get update

Currently there is a bionic build for it.  This installs it and updates systemd files to run it as a service. We will be putting out documentation on it soon

**Comment by JohnSully** [comment]
If the PPA isn't sufficient feel free to post a comment here.  Closing for now.

**Comment by steamboatid** [comment]
so please update the readme to include this ppa.

thanks

**Comment by debrouxl** [comment]
I would be interested in open source KeyDB packages for Debian proper, versions 9 (stretch) and 10 (buster).
Besides your existing PPA packaging definitions and Debian packaging definitions for Redis, you might be able to leverage infrastructure such as the openSUSE Build Service.

**Comment by k0fi** [comment]
Does not work on Debian 9.9

```
root@front:/etc/apt/sources.list.d#  apt-get update
Hit:1 http://security.debian.org stretch/updates InRelease
Ign:2 http://httpredir.debian.org/debian stretch InRelease                                          
Hit:3 http://httpredir.debian.org/debian stretch-updates InRelease                                  
Hit:4 http://httpredir.debian.org/debian stretch Release                      
Hit:5 https://download.docker.com/linux/debian stretch InRelease              
Ign:6 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal InRelease    
Hit:7 https://download.keydb.dev/keydb-ppa ./ InRelease                      
Ign:9 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal Release     
Ign:10 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main all Packages
Ign:11 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main amd64 Packages
Ign:12 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main Translation-en
Ign:10 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main all Packages
Ign:11 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main amd64 Packages
Ign:12 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main Translation-en
Ign:10 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main all Packages
Ign:11 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main amd64 Packages
Ign:12 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main Translation-en
Ign:10 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main all Packages
Ign:11 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main amd64 Packages
Ign:12 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main Translation-en
Ign:10 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main all Packages
Ign:11 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main amd64 Packages
Ign:12 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main Translation-en
Ign:10 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main all Packages
Err:11 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main amd64 Packages
  404  Not Found [IP: 91.189.95.83 80]
Ign:12 http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal/main Translation-en
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu focal Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/eqalpha/keydb-server/ubuntu/dists/focal/main/binary-amd64/Packages  404  Not Found [IP: 91.189.95.83 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
Appreciate your hints.

**Comment by steamboatid** [comment]
try use bionic instead of focal for apt sources.list

**Comment by sts** [comment]
@JohnSully Would it be possible to setup proper repositories for debian too? I can recommend https://github.com/rcrowley/freight which allows to store multiple versions of a package in the same repository.

**Comment by sts** [comment]
I created a script which initializes a new freight repository and imports all packages from https://download.keydb.dev/packages/deb (debian/ubuntu).

Take a look at the following gist:
 https://gist.github.com/sts/71200ca957dad08fa70bb0866b8795d4

To use:
- Install freight
- Generate a GPG Key
- Change repository location in script variables
- Run script
- Profit!

**Comment by benschermel** [comment]
@sts, Thanks Stefan for the recommendation and script. Looks like a good option

I will put this on my list to test and integrate with our builds/releases

**Comment by sts** [comment]
@benschermel can we maybe reopen the issue so we keep this on track? it would be great if we could remove docker containers around keydb instances and switch to plain debian repos.

**Comment by JohnSully** [comment]
Reopening as requested.

**Comment by sts** [comment]
hi @benschermel. Is this something you are going to consider anytime? Would make it much easier to install keydb and keep it up-to-date in non-docker environments.

**Comment by benschermel** [comment]
Hi @sts, 

Agree this makes a lot of sense here, and unfortunately it had got put on the back-burner for a bit. I want to add support for focal builds as well and will be revisiting using freight this month. I am currently targeting to get this implemented by end of March.

**Comment by benschermel** [comment]
Hi @sts,

I have updated our distribution to use freight now... it seems to work a lot better and has enabled us to provide a single source for all our ubuntu/debian packages. Thanks for the suggestion, much appreciated! You should be able to install buster/stretch packages now. I have also added in focal packages.

You can use the commands below to install KeyDB:
```
$ echo "deb https://download.keydb.dev/open-source-dist $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/keydb.list
$ sudo wget -O /etc/apt/trusted.gpg.d/keydb.gpg https://download.keydb.dev/open-source-dist/keyring.gpg
$ sudo apt update
$ sudo apt install keydb
```
You can find detailed instructions on how to download/install the debian packages in the [updated docs](https://docs.keydb.dev/docs/ppa-deb)

**Comment by botzill** [comment]
Hi.

Still I see an old version of keydb on that PPA:

```
Package: keydb
Version: 5:5.3.1-1chl1~bionic1
```

Is there a way to get the latest version or to build it by ourselves?

**Comment by benschermel** [comment]
Hi @botzill,

The freight repository makes available all packages listed [here ](https://download.keydb.dev/pkg/open_source/deb/ubuntu18.04_bionic/amd64/keydb_all_versions/) including the latest 6.0.18 version. By default when installing, the latest version should be installed. When upgrading packages following installation you can  `apt install --only-upgrade keydb` to upgrade to the next version.

If you want to build KeyDB yourself, please see: https://docs.keydb.dev/docs/build. 

Following the instructions:
```
$ echo "deb https://download.keydb.dev/open-source-dist $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/keydb.list
$ sudo wget -O /etc/apt/trusted.gpg.d/keydb.gpg https://download.keydb.dev/open-source-dist/keyring.gpg
$ sudo apt update
$ sudo apt install keydb
```

you can run `apt-cache policy keydb` to get the following:
![image](https://user-images.githubusercontent.com/43507366/113318965-fb36ce00-92de-11eb-8300-0479be50f4e1.png)

Hope this helps to clarify, if I am not understanding your question please elaborate

**Comment by botzill** [comment]
thx, I thought it's using the old version only, what you send above is exactly what I asked for.

Thx!

**Comment by botzill** [comment]
But now when I start it with:

```
systemctl start keydb
```

We get at some point this error:

```
Apr  6 18:16:26 ns3093068 systemd[1]: keydb-server.service: Start operation timed out. Terminating.
Apr  6 18:16:26 ns3093068 keydb_6380[10985]: User requested shutdown...
Apr  6 18:16:26 ns3093068 keydb_6380[10985]: Saving the final RDB snapshot before exiting.
Apr  6 18:16:26 ns3093068 keydb_6380[10985]: DB saved on disk
Apr  6 18:16:26 ns3093068 keydb_6380[10985]: Removing the pid file.
Apr  6 18:16:26 ns3093068 keydb_6380[10985]: KeyDB is now ready to exit, bye bye...
Apr  6 18:16:26 ns3093068 systemd[1]: keydb-server.service: Failed with result 'timeout'.
Apr  6 18:16:26 ns3093068 systemd[1]: Failed to start Advanced key-value store.
```

how do we start that on ubuntu? It's a clean DB.
